import os
import secrets
import tempfile

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "timestat.db")

DEFAULT_CATEGORIES = [
    "Managing Infrastructure",
    "Working on Scripts",
    "Working on Wiki Documentation",
    "Working on Playbooks",
    "Practicing IR",
    "In Practice Competition",
    "Research",
    "TryHackMe",
    "Team Coordination",
    "Mentoring/Training Others",
    "Other",
]
WEEK_SECONDS = 7 * 24 * 60 * 60
NOTE_MAX_LENGTH = 200
CATEGORY_MAX_LENGTH = 80
BACKUP_RETENTION_DAYS = 14
AUTH_WINDOW_SECONDS = 5 * 60
LOGIN_MAX_ATTEMPTS = 8
ADMIN_LOGIN_MAX_ATTEMPTS = 5
# Per-account lockout threshold (independent of source IP) so that rotating IPs
# (botnets / proxy pools) can't bypass per-IP rate limiting. Keyed on username
# alone, so a known account can't be brute-forced faster than this many failed
# attempts within AUTH_WINDOW_SECONDS regardless of how many IPs the attacker
# uses. Kept higher than LOGIN_MAX_ATTEMPTS to give legitimate users headroom
# across multiple devices.
LOGIN_ACCOUNT_MAX_ATTEMPTS = 12
DEFAULT_RECENT_LIMIT = 10
MAX_RECENT_LIMIT = 200
MAX_SESSION_RUNNING_HOURS = 8
# How far back the collaboration "new starts" feed (/api/status?collab_since=)
# is allowed to look. A client can otherwise request a huge window and force a
# large result set on every poll. Also bounded in rows by COLLAB_EVENT_LIMIT.
COLLAB_SINCE_MAX_AGE_SECONDS = 24 * 60 * 60
COLLAB_EVENT_LIMIT = 50

# Number of trusted reverse proxy hops in front of this app. When 0 (default),
# the app is assumed to receive connections directly and X-Forwarded-For is
# never trusted for things like rate-limit keys. Only set this to a positive
# number when a known, trusted number of reverse proxies (e.g. nginx) sit in
# front of the app and are configured to overwrite (not append to)
# X-Forwarded-For.
DEFAULT_TRUSTED_PROXY_COUNT = 0


def load_env_file(path: str) -> None:
    if not os.path.exists(path):
        return

    with open(path, encoding="utf-8") as env_file:
        for raw_line in env_file:
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip()
            if not key:
                continue
            if (
                len(value) >= 2
                and value[0] == value[-1]
                and value[0] in ("'", '"')
            ):
                value = value[1:-1]
            os.environ.setdefault(key, value)


# Candidate env files that ADMIN_CODE may be persisted to, in priority order.
# <BASE_DIR>/.env covers local dev and same-dir deployments (deploy.sh copies
# the repo to /opt/timestat, so BASE_DIR/.env resolves there). The /etc path
# is the systemd deploy target written by deploy.sh.
ADMIN_CODE_CANDIDATE_PATHS = (
    os.path.join(BASE_DIR, ".env"),
    "/etc/timestat/timestat.env",
)

# Lines stripped from the chosen env file when ADMIN_CODE is written, so the
# retired username/password pair (and any prior ADMIN_CODE) don't linger as
# dead/confusing config.
_ADMIN_CODE_STRIP_PREFIXES = (
    "ADMIN_USERNAME=",
    "ADMIN_PASSWORD=",
    "ADMIN_CODE=",
)


def generate_admin_code() -> str:
    # 15 random bytes -> ~20 URL-safe chars (~128 bits of entropy). Admin
    # access is strictly more privileged than a user login, so the code is
    # intentionally much stronger than the 6-digit (~20-bit) user codes
    # generated by utils.helpers.generate_login_code; 5 attempts per 5 min
    # (config.ADMIN_LOGIN_MAX_ATTEMPTS) makes even online brute force
    # infeasible against this entropy level.
    return secrets.token_urlsafe(15)


def _line_starts_with_any(line: str, prefixes: tuple[str, ...]) -> bool:
    stripped = line.strip()
    return any(stripped.startswith(prefix) for prefix in prefixes)


def ensure_admin_code(code: str) -> str:
    # Persist ADMIN_CODE=<code> to the first writable candidate env file.
    # Existing ADMIN_USERNAME= / ADMIN_PASSWORD= / ADMIN_CODE= lines are
    # stripped from the chosen file. The write is atomic (mkstemp + replace)
    # so concurrent gunicorn workers racing on startup can't corrupt it or
    # append duplicate keys. Returns the path written, or raises RuntimeError
    # if no candidate is writable - which is a hard fail because silently
    # keeping the code in-memory only would rotate it on every restart and
    # lock the admin out as soon as the process dies.
    for path in ADMIN_CODE_CANDIDATE_PATHS:
        existing = ""
        try:
            with open(path, encoding="utf-8") as fh:
                existing = fh.read()
        except FileNotFoundError:
            existing = ""
        except OSError:
            continue

        kept = [
            line
            for line in existing.splitlines()
            if not _line_starts_with_any(line, _ADMIN_CODE_STRIP_PREFIXES)
        ]
        kept.append(f"ADMIN_CODE={code}")
        new_content = "\n".join(kept).rstrip() + "\n"

        parent = os.path.dirname(path) or "."
        try:
            fd, tmp_path = tempfile.mkstemp(prefix=".env.", dir=parent)
            try:
                with os.fdopen(fd, "w", encoding="utf-8") as fh:
                    fh.write(new_content)
                os.replace(tmp_path, path)
            except OSError:
                try:
                    os.unlink(tmp_path)
                except OSError:
                    pass
                raise
        except OSError:
            continue

        return path

    raise RuntimeError(
        "Could not persist ADMIN_CODE to any env file. Tried: "
        + ", ".join(ADMIN_CODE_CANDIDATE_PATHS)
        + ". Manually add ADMIN_CODE=<your-code> to one of them and restart."
    )
